* Individual project for the course - High Performance Programming, 10.0 c

* Usage

- *make run* - runs a random simulation with graphics turned on. Type the following to change settings:
  - N=X - sets the grid size to X*X.
  - TS=X - changes the number of steps to evolve to X.
  - TT=X - pause for X seconds between evolution steps.
  - G=X - turn graphics on/off if G = 1/0 respectively.
  - T=X - run the simulation with X threads in parallel.

The following command will use 8 threads to run a simulation with a 500x500 grid in 1000 time-steps.  
#+begin_src shell
make run N=500 TS=1000 T=8 
#+end_src

- *make profile* - runs profiling for an instance with N = 2000 in 100 time-steps.

- *make time* - runs time tests for instances where N = 500, 1000, 1500, 2000, 5000, 10000 and 20000. 100 time-steps each.

- *make clean* - cleaning up..

- Note: set T=x after any make command to set the number of threads. 
Example: make time T=8 - will run with 8 threads
         make time T=2 - will run with 2 threads.

* Notes
- The current setting uses the -O3 compiler flag. It is recommended to change it to -Ofast if your gcc version support it.

- The code used for graphics in this program (found inside graphics/) is not written by me (except for some minor changes), and I take no credit for it.
